version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    depends_on:
      - postgres
    networks:
      - postgres
    ports:
      - 3000:3000
    environment:
      - MB_PASSWORD_COMPLEXITY=weak
      - MB_PASSWORD_LENGTH=2
      - MB_DB_DBNAME=metabase
      - MB_DB_TYPE=postgres
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=postgres
      - MB_DB_PORT=5432
  adminer:
    build: .
    container_name: adminer
    depends_on:
      - postgres
    networks:
      - postgres
    ports:
      - 8080:80

networks:
  metabase:
    name: metabase

volumes:
  postgres:
    name: postgres
